hyperparameters:
  epochs: 50
  optimizer: "Adam"
  loss: "binary_crossentropy"
dropout:
  first: 0
  second: 0
  third: 0
  fourth: 0
metrics:
  fbeta: 1
callback:
  checkpoint: true
  path_checkpoint: weights/weights
  tensorboard: false
  path_log: /content/log
other:
  fit: true
  save: false
  load_weights: true
  path_weights: weights/weights