hyperparameters:
  epochs: 100
  optimizer: "Adam"
  loss: "binary_crossentropy"
metrics:
  fbeta: 1
callback:
  checkpoint: true
  path_checkpoint: weights
  tensorboard: true
  path_log: /content/log
other:
  fit: true
  save: true
  load_weights: true
  path_weights: weights/weights
  path_save: full/