hyperparameters:
  epochs: 10
  optimizer: "Adam"
  loss: "binary_crossentropy"
metrics:
  fbeta: 1
callback:
  checkpoint: false
  path_checkpoint: weights/weights
  tensorboard: false
  path_log: /content/log
other:
  fit: true
  save: false
  load_weights: false
  path_weights: weights/weights
  path_save: full/